const CartListTypes = {
    ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
    ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
    ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",

    FETCH_ITEM_FROM_CART_CHECK: "FETCH_ITEM_FROM_CART_CHECK",

    FETCH_ITEM_FROM_CART_REQUEST: "FETCH_ITEM_FROM_CART_REQUEST",
    FETCH_ITEM_FROM_CART_SUCCESS: "FETCH_ITEM_FROM_CART_SUCCESS",
    FETCH_ITEM_FROM_CART_ERROR: "FETCH_ITEM_FROM_CART_ERROR",

    REMOVE_FROM_CART_REQUEST: "REMOVE_FROM_CART_REQUEST",
    REMOVE_FROM_CART_SUCCESS: "REMOVE_FROM_CART_SUCCESS",
    REMOVE_FROM_CART_ERROR: "REMOVE_FROM_CART_ERROR"
};

export default CartListTypes;