const OrderTypes = {
    SEND_ORDER_REQUEST: "SEND_ORDER_REQUEST",
    SEND_ORDER_SUCCESS: "SEND_ORDER_SUCCESS",
    SEND_ORDER_FAILURE: "SEND_ORDER_FAILURE",

    FETCH_ORDER_REQUEST: "FETCH_ORDER_REQUEST",
    FETCH_ORDER_SUCCESS: "FETCH_ORDER_SUCCESS",
    FETCH_ORDER_FAILURE: "FETCH_ORDER_FAILURE"
};

export default OrderTypes;