const SearchTypes = {
    NEW_PRODUCT_SEARCH_REQUEST: "NEW_PRODUCT_SEARCH_REQUEST",
    NEW_PRODUCT_SEARCH_SUCCESS: "NEW_PRODUCT_SEARCH_SUCCESS",
    NEW_PRODUCT_SEARCH_ERROR: "NEW_PRODUCT_SEARCH_ERROR",

    SEARCH_ITEM_REQUEST: "SEARCH_ITEM_REQUEST",
    SEARCH_ITEM_SUCCESS: "SEARCH_ITEM_SUCCESS",
    SEARCH_ITEM_ERROR: "SEARCH_ITEM_ERROR",

    SEARCH_ALL_CAT_REQUEST: "SEARCH_ALL_CAT_REQUEST",
    SEARCH_ALL_CAT_SUCCESS: "SEARCH_ALL_CAT_SUCCESS",
    SEARCH_ALL_CAT_ERROR: "SEARCH_ALL_CAT_ERROR",

    SEARCH_CAT_REQUEST: "SEARCH_CAT_REQUEST",
    SEARCH_CAT_SUCCESS: "SEARCH_CAT_SUCCESS",
    SEARCH_CAT_ERROR: "SEARCH_CAT_ERROR"
};

export default SearchTypes;