const SearchTypes = {
    NEW_PRODUCT_SEARCH_REQUEST: "NEW_PRODUCT_SEARCH_REQUEST",
    NEW_PRODUCT_SEARCH_SUCCESS: "NEW_PRODUCT_SEARCH_SUCCESS",
    NEW_PRODUCT_SEARCH_ERROR: "NEW_PRODUCT_SEARCH_ERROR",

    SEARCH_ITEM_REQUEST: "SEARCH_ITEM_REQUEST",
    SEARCH_ITEM_SUCCESS: "SEARCH_ITEM_SUCCESS",
    SEARCH_ITEM_ERROR: "SEARCH_ITEM_ERROR"
};

export default SearchTypes;