const WishListTypes = {
    ADD_TO_WISH_LIST_REQUEST: "ADD_TO_WISH_LIST_REQUEST",
    ADD_TO_WISH_LIST_SUCCESS: "ADD_TO_WISH_LIST_SUCCESS",
    ADD_TO_WISH_LIST_FAILURE: "ADD_TO_WISH_LIST_FAILURE",

    FETCH_ITEM_FROM_WISH_LIST_CHECK: "FETCH_ITEM_FROM_WISH_LIST_CHECK",

    FETCH_ITEM_FROM_WISH_LIST_REQUEST: "FETCH_ITEM_FROM_WISH_LIST_REQUEST",
    FETCH_ITEM_FROM_WISH_LIST_SUCCESS: "FETCH_ITEM_FROM_WISH_LIST_SUCCESS",
    FETCH_ITEM_FROM_WISH_LIST_ERROR: "FETCH_ITEM_FROM_WISH_LIST_ERROR",

    REMOVE_FROM_WISH_LIST_REQUEST: "REMOVE_FROM_WISH_LIST_REQUEST",
    REMOVE_FROM_WISH_LIST_SUCCESS: "REMOVE_FROM_WISH_LIST_SUCCESS",
    REMOVE_FROM_WISH_LIST_ERROR: "REMOVE_FROM_WISH_LIST_ERROR"
};

export default WishListTypes;