const AuthTypes = {
    ANONYMOUS_LOGIN: "ANONYMOUS_LOGIN",
    NOT_ANONYMOUS_LOGIN: "NOT_ANONYMOUS_LOGIN",

    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",

    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",

    SIGN_UP_REQUEST: "SIGN_UP_REQUEST",
    SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
    SIGN_UP_FAILURE: "SIGN_UP_FAILURE",

    VERIFY_REQUEST: "VERIFY_REQUEST",
    VERIFY_SUCCESS: "VERIFY_SUCCESS",
    VERIFY_ERROR: "VERIFY_ERROR"
};

export default AuthTypes;