const ItemTypes = {
    ADD_ITEM_REQUEST: "ADD_ITEM_REQUEST",
    ADD_ITEM_SUCCESS: "ADD_ITEM_SUCCESS",
    ADD_ITEM_FAILURE: "ADD_ITEM_FAILURE",

    GET_ITEM_DETAIL_REQUEST: "GET_ITEM_DETAIL_REQUEST",
    GET_ITEM_DETAIL_SUCCESS: "GET_ITEM_DETAIL_SUCCESS",
    GET_ITEM_DETAIL_ERROR: "GET_ITEM_DETAIL_ERROR",

    FETCH_MY_ITEM_REQUEST: "FETCH_MY_ITEM_REQUEST",
    FETCH_MY_ITEM_SUCCESS: "FETCH_MY_ITEM_SUCCESS",
    FETCH_MY_ITEM_ERROR: "FETCH_MY_ITEM_ERROR",

    EDIT_MY_ITEM_REQUEST: "EDIT_MY_ITEM_REQUEST",
    EDIT_MY_ITEM_SUCCESS: "EDIT_MY_ITEM_SUCCESS",
    EDIT_MY_ITEM_ERROR: "EDIT_MY_ITEM_ERROR"
};

export default ItemTypes;