const AddCatTypes = {
    ADD_CATEGORY_REQUEST: "ADD_CATEGORY_REQUEST",
    ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
    ADD_CATEGORY_ERROR: "ADD_CATEGORY_ERROR",

    ADD_SUB_CATEGORY_REQUEST: "ADD_SUB_CATEGORY_REQUEST",
    ADD_SUB_CATEGORY_SUCCESS: "ADD_SUB_CATEGORY_SUCCESS",
    ADD_SUB_CATEGORY_ERROR: "ADD_SUB_CATEGORY_ERROR",
};

export default AddCatTypes;